name: Build

on: [push, pull_request]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      
      - name: Go build
        run: go build .
  
      - name: Launch Postgres
        run: docker run -d --env POSTGRES_USER=transiter --env POSTGRES_PASSWORD=transiter --env POSTGRES_DB=transiter -p 5432:5432 postgres:12

      - name: Go test
        run: go test ./...
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/transiter:latest
          outputs: type=docker
          context: .

      - name: End-to-end tests (setup)
        run: docker-compose -f tests/endtoend/compose.yml up --build --detach sourceserver transiter db

      - name: End-to-end tests (run)
        run: docker-compose -f tests/endtoend/compose.yml up --build --exit-code-from testrunner testrunner

      - name: Linter
        run: go install honnef.co/go/tools/cmd/staticcheck@2022.1 && staticcheck ./...